In [1]:
import numpy as np
import pandas as pd

In [2]:
credits = pd.read_csv('tmdb_5000_credits.csv')
movies = pd.read_csv('tmdb_5000_movies.csv')

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [6]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [7]:
movies = movies.merge(credits, on='title')

In [8]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [9]:
movies = movies[['genres','id','keywords','title','overview','cast','crew']]

In [10]:
movies.head(1)

,genres,id,keywords,title,overview,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [11]:
movies.isnull().sum()

genres      0
id          0
keywords    0
title       0
overview    3
cast        0
crew        0
dtype: int64

In [12]:
movies.dropna(inplace=True)

In [13]:
movies.isnull().sum()

genres      0
id          0
keywords    0
title       0
overview    0
cast        0
crew        0
dtype: int64

In [14]:
movies.duplicated().sum()

0

In [15]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [16]:
#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]' now we need to pick the genres namee from this list but its not a list actually it is a string and for converting the string looking like a list into a real list we are going to use ast module
#lets first build a function that will take the genres one by one and convert them 
import ast
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [17]:
movies['genres'] = movies['genres'].apply(convert)

In [18]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
movies['keywords']=movies['keywords'].apply(convert)

In [20]:
movies.head(1)

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [21]:
def convert3(obj):
    L=[]
    counter = 0
    for i in ast.literal_eval(obj):
        if counter < 3:
            L.append(i['name'])
            counter = counter + 1
        else :
            break
    return L

In [22]:
movies['cast']=movies['cast'].apply(convert3)

In [23]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [24]:
movies['crew']=movies['crew'].apply(fetch_director)

In [25]:
movies.head(1)

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [26]:
#now we will covert the overview into list format as it is in a string format so that we can make it operational with the columns
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [27]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [28]:
movies['genres']= movies['genres'].apply(lambda x:[i.replace(' ','') for i in x])

In [29]:
movies['keywords']= movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

In [30]:
movies['cast']= movies['cast'].apply(lambda x:[i.replace(' ','') for i in x])

In [31]:
movies['crew']= movies['crew'].apply(lambda x:[i.replace(' ','') for i in x])

In [32]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,"[Action, Adventure, ScienceFiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [33]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [34]:
movies.head()

,genres,id,keywords,title,overview,cast,crew,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,"[Action, Adventure, ScienceFiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [35]:
new_df = movies[['id','title','tags']]

In [36]:
new_df.head()

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [37]:
new_df['tags']= new_df['tags'].apply(lambda x:' '.join(x))

C:\Users\milind\AppData\Local\Temp\ipykernel_23140\3391018727.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']= new_df['tags'].apply(lambda x:' '.join(x))

In [38]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [39]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\milind\AppData\Local\Temp\ipykernel_23140\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [40]:
import nltk

In [41]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [42]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [43]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\milind\AppData\Local\Temp\ipykernel_23140\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [44]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [45]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [46]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [47]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [48]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [49]:
len(cv.get_feature_names_out())

5000

In [50]:
features = cv.get_feature_names_out()

In [51]:
print(features)

['000' '007' '10' ... 'zone' 'zoo' 'zooeydeschanel']

In [52]:
stem("in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron")

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [53]:
from sklearn.metrics.pairwise import cosine_similarity

In [54]:
similarity = cosine_similarity(vectors)

In [55]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 1.0000000000000002),
 (1214, 0.28676966733820225),
 (2405, 0.26901379342448517),
 (3728, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.25038669783359574),
 (582, 0.24511108480187255),
 (1202, 0.24455799402225925),
 (1192, 0.2367785320221084),
 (61, 0.23179316248638276),
 (778, 0.23174488732966073),
 (4046, 0.2278389747471728),
 (1916, 0.2252817784447915),
 (2782, 0.21853668936906193),
 (172, 0.21239769762143662),
 (972, 0.2108663315950723),
 (322, 0.2105263157894737),
 (2329, 0.20443988269091456),
 (3606, 0.20437977982832192),
 (260, 0.20395079136182276),
 (151, 0.2029530274475215),
 (4190, 0.2029530274475215),
 (1440, 0.20277677641345318),
 (74, 0.2024645717996314),
 (1087, 0.2020475485519274),
 (3671, 0.1979082783981174),
 (973, 0.19767387315371682),
 (577, 0.1976738731537168),
 (47, 0.19672236884115843),
 (2969, 0.1925214071641298),
 (942, 0.19134594929397597),
 (495, 0.19088542889273336),
 (1199, 0.19088542889273336),
 (305, 0.19007487139298027),
 (4, 0.1892994097121204),
 (4405, 0.18731716231633883),
 (94, 0.1873171623163388),
 (27, 0.18693292157876878),
 (3325, 0.1860807318911967),
 (1273, 0.18394180184548975),
 (1327, 0.18394180184548975),
 (2997, 0.1813690625275029),
 (3997, 0.18074256993863339),
 (83, 0.17996850826633903),
 (1069, 0.17954621161490197),
 (220, 0.1777046633277277),
 (184, 0.177343107178349),
 (1319, 0.17699808135119718),
 (168, 0.17521916101261562),
 (2200, 0.17521916101261562),
 (4336, 0.17521916101261562),
 (931, 0.1748149640244195),
 (36, 0.17316974359835272),
 (373, 0.17292861596651865),
 (300, 0.1711905958155815),
 (3536, 0.1711905958155815),
 (3160, 0.17040572913692198),
 (1978, 0.16943474841747155),
 (661, 0.1675415633166782),
 (529, 0.16742770563222897),
 (1827, 0.16742770563222897),
 (91, 0.16692446522239718),
 (41, 0.16563698349810535),
 (67, 0.16452254913212452),
 (150, 0.16426202236672155),
 (1533, 0.16222142113076254),
 (342, 0.16122923187750418),
 (595, 0.16059101370939324),
 (31, 0.15907119074394446),
 (2511, 0.15907119074394446),
 (1176, 0.15789473684210528),
 (4008, 0.15737789507292674),
 (2727, 0.15609763526361567),
 (149, 0.15511334686589626),
 (838, 0.1540171257313038),
 (26, 0.15389675281277312),
 (187, 0.15389675281277312),
 (1379, 0.152008377581442),
 (111, 0.15018785229652767),
 (1342, 0.15018785229652767),
 (311, 0.15018785229652765),
 (52, 0.14843120879858804),
 (513, 0.14843120879858804),
 (2071, 0.14808721943977307),
 (7, 0.14673479641335554),
 (2756, 0.14659886790209342),
 (127, 0.14601068654819693),
 (579, 0.14567913668701626),
 (581, 0.14567913668701626),
 (108, 0.14509525002200235),
 (1295, 0.14509525002200235),
 (466, 0.14509525002200233),
 (1392, 0.14421498760030763),
 (1475, 0.1442149876003076),
 (1353, 0.14350946197048198),
 (1934, 0.14350946197048198),
 (275, 0.1433848336691011),
 (294, 0.1433848336691011),
 (3352, 0.1433848336691011),
 (1054, 0.1419745572840903),
 (1271, 0.1419745572840903),
 (490, 0.14159846508095775),
 (1484, 0.14159846508095775),
 (413, 0.1411956236812263),
 (461, 0.1411956236812263),
 (568, 0.1411956236812263),
 (2492, 0.1411956236812263),
 (95, 0.14048787173725413),
 (17, 0.13977653617040256),
 (46, 0.1391037210186643),
 (3407, 0.1391037210186643),
 (1961, 0.13872950617564817),
 (56, 0.13834289277321493),
 (249, 0.13834289277321493),
 (1325, 0.13834289277321493),
 (3779, 0.13834289277321493),
 (72, 0.13710212427677043),
 (843, 0.13710212427677043),
 (859, 0.13710212427677043),
 (2165, 0.13710212427677043),
 (4538, 0.13629325512727639),
 (476, 0.13530201829834768),
 (505, 0.13530201829834768),
 (668, 0.13530201829834768),
 (935, 0.13530201829834768),
 (3980, 0.13530201829834768),
 (1804, 0.13518451760896877),
 (4348, 0.13497638119975428),
 (1320, 0.13476498501489081),
 (158, 0.13369695534647594),
 (502, 0.13369695534647594),
 (777, 0.13369695534647594),
 (126, 0.13334518676566626),
 (1556, 0.13334518676566626),
 (1369, 0.1324532357065044),
 (2374, 0.1324532357065044),
 (2580, 0.1324532357065044),
 (4077, 0.13157894736842107),
 (2129, 0.13124359177794215),
 (1013, 0.12988108336653278),
 (2177, 0.12988108336653278),
 (3620, 0.12988108336653278),
 (134, 0.12977713690461004),
 (368, 0.12977713690461004),
 (1770, 0.12977713690461004),
 (2869, 0.12892051277806202),
 (14, 0.12824729401064427),
 (138, 0.12824729401064427),
 (369, 0.12824729401064427),
 (1084, 0.12824729401064427),
 (2682, 0.12824729401064427),
 (4228, 0.12824729401064427),
 (487, 0.12725695259515557),
 (773, 0.12725695259515557),
 (2968, 0.12725695259515557),
 (937, 0.126673647984535),
 (2476, 0.12565617248750865),
 (1737, 0.12565617248750863),
 (166, 0.12515654358043973),
 (754, 0.12515654358043973),
 (2446, 0.12515654358043973),
 (3626, 0.12515654358043973),
 (483, 0.12487810821089254),
 (1094, 0.12487810821089254),
 (1156, 0.12487810821089254),
 (2648, 0.12487810821089254),
 (102, 0.12462194771917919),
 (84, 0.12361284651454937),
 (208, 0.12262786789699316),
 (3374, 0.12262786789699316),
 (1874, 0.12262786789699313),
 (438, 0.12227899701112963),
 (557, 0.12227899701112963),
 (1297, 0.12227899701112963),
 (2327, 0.12166606584807191),
 (2670, 0.12166606584807191),
 (3081, 0.12166606584807191),
 (139, 0.12072654548783007),
 (68, 0.1204950466257556),
 (781, 0.1204950466257556),
 (1002, 0.1204950466257556),
 (1272, 0.1204950466257556),
 (1654, 0.1204950466257556),
 (1000, 0.11980845957463077),
 (549, 0.11959121830873498),
 (870, 0.11959121830873498),
 (900, 0.11959121830873498),
 (3233, 0.11959121830873498),
 (1045, 0.11846977555181847),
 (1829, 0.11846977555181847),
 (2056, 0.11846977555181847),
 (2737, 0.11846977555181847),
 (4673, 0.11846977555181847),
 (3719, 0.11803342130469506),
 (1669, 0.11803342130469505),
 (1711, 0.11803342130469505),
 (2785, 0.11803342130469505),
 (3998, 0.11803342130469505),
 (160, 0.11712303424679457),
 (182, 0.11707322644771176),
 (278, 0.11707322644771176),
 (454, 0.11707322644771176),
 (1613, 0.11707322644771176),
 (2280, 0.11707322644771176),
 (28, 0.116543309349613),
 (122, 0.116543309349613),
 (422, 0.116543309349613),
 (678, 0.116543309349613),
 (589, 0.1163350101494222),
 (2543, 0.11587244366483038),
 (1493, 0.11551284429847784),
 (3210, 0.11506355109724453),
 (189, 0.1147078669352809),
 (1218, 0.1147078669352809),
 (236, 0.11470786693528087),
 (1299, 0.11470786693528087),
 (85, 0.1141270638770543),
 (432, 0.11357771260606365),
 (1414, 0.11357771260606365),
 (50, 0.11295649894498103),
 (1612, 0.11295649894498103),
 (123, 0.1124803176664619),
 (420, 0.1124803176664619),
 (536, 0.1124803176664619),
 (889, 0.11243619908556624),
 (3145, 0.11239029738980327),
 (256, 0.11164843913471803),
 (808, 0.11164843913471803),
 (1346, 0.11164843913471803),
 (1571, 0.11164843913471803),
 (2368, 0.11141412945539662),
 (3307, 0.11141412945539662),
 (1508, 0.11141412945539661),
 (87, 0.11128297681493143),
 (121, 0.11128297681493143),
 (232, 0.11128297681493143),
 (4468, 0.11128297681493143),
 (206, 0.11092107999698035),
 (238, 0.11092107999698035),
 (228, 0.11037769642208699),
 (81, 0.11020775375559676),
 (1570, 0.11020775375559674),
 (3426, 0.10968169942141637),
 (21, 0.10968169942141635),
 (449, 0.10968169942141635),
 (1029, 0.10968169942141635),
 (1941, 0.10968169942141635),
 (2144, 0.10968169942141635),
 (3006, 0.10968169942141635),
 (692, 0.10936965981495178),
 (200, 0.10882143751650175),
 (627, 0.10882143751650175),
 (653, 0.10882143751650175),
 (1520, 0.10882143751650175),
 (307, 0.10876595882948199),
 (5, 0.10838874619051501),
 (740, 0.10838874619051501),
 (3091, 0.10838874619051501),
 (3628, 0.10838874619051501),
 (786, 0.10814761408717502),
 (3496, 0.10814761408717502),
 (4777, 0.10814761408717502),
 (229, 0.1074861545850028),
 (572, 0.10743376064838502),
 (939, 0.1068366854693644),
 (332, 0.106676149412533),
 (472, 0.106676149412533),
 (1235, 0.106676149412533),
 (170, 0.10650358071057624),
 (262, 0.10650358071057624),
 (1164, 0.10619884881071831),
 (1497, 0.10619884881071831),
 (1741, 0.10619884881071831),
 (2157, 0.10619884881071831),
 (2630, 0.10619884881071831),
 (4133, 0.10619884881071831),
 (467, 0.10559715077387793),
 (541, 0.10559715077387793),
 (1492, 0.10559715077387793),
 (131, 0.10526315789473685),
 (295, 0.10526315789473685),
 (2068, 0.10526315789473685),
 (3338, 0.10526315789473685),
 (2494, 0.10471347707292386),
 (75, 0.10390486669322622),
 (223, 0.10390486669322622),
 (687, 0.10390486669322622),
 (814, 0.10390486669322622),
 (1193, 0.10390486669322622),
 (1767, 0.10390486669322622),
 (2813, 0.10390486669322622),
 (654, 0.10385162309931599),
 (2435, 0.10385162309931599),
 (105, 0.1037571695799112),
 (233, 0.1037571695799112),
 (624, 0.1037571695799112),
 (2319, 0.1037571695799112),
 (2452, 0.1037571695799112),
 (2517, 0.1037571695799112),
 (3053, 0.1037571695799112),
 (3619, 0.1037571695799112),
 (3837, 0.1037571695799112),
 (1451, 0.10301070542879115),
 (10, 0.10259783520851541),
 (1080, 0.10259783520851541),
 (3150, 0.10259783520851541),
 (3632, 0.10259783520851541),
 (3753, 0.10259783520851541),
 (3872, 0.10259783520851541),
 (4095, 0.10259783520851541),
 (2102, 0.10218988991416095),
 (2758, 0.10147651372376076),
 (3659, 0.10147651372376076),
 (3952, 0.10147651372376076),
 (3439, 0.10138838820672659),
 (508, 0.101338918387628),
 (1292, 0.101338918387628),
 (2243, 0.10133891838762799),
 (1401, 0.10060545457319173),
 (1435, 0.10060545457319173),
 (2095, 0.10060545457319173),
 (312, 0.10012523486435178),
 (330, 0.10012523486435178),
 (643, 0.10012523486435178),
 (986, 0.10012523486435178),
 (1035, 0.10012523486435178),
 (1610, 0.10012523486435178),
 (35, 0.09933992677987831),
 (157, 0.09933992677987831),
 (319, 0.09933992677987831),
 (325, 0.09933992677987831),
 (715, 0.09933992677987831),
 (1075, 0.09933992677987831),
 (1278, 0.09933992677987831),
 (1880, 0.09933992677987831),
 (2049, 0.09933992677987831),
 (4016, 0.09933992677987831),
 (4196, 0.09933992677987831),
 (4490, 0.09933992677987831),
 (363, 0.09909250441117726),
 (491, 0.09909250441117726),
 (266, 0.0989541391990587),
 (445, 0.0989541391990587),
 (510, 0.0989541391990587),
 (3618, 0.0989541391990587),
 (3781, 0.0989541391990587),
 (3933, 0.0989541391990587),
 (1771, 0.09836118442057921),
 (410, 0.0978231976089037),
 (480, 0.0978231976089037),
 (535, 0.0978231976089037),
 (898, 0.0978231976089037),
 (1107, 0.0978231976089037),
 (1397, 0.0978231976089037),
 (1819, 0.0978231976089037),
 (2249, 0.0978231976089037),
 (33, 0.09733285267845754),
 (148, 0.09733285267845754),
 (263, 0.09733285267845754),
 (878, 0.09733285267845754),
 (1154, 0.09733285267845754),
 (1723, 0.09733285267845754),
 (1938, 0.09733285267845754),
 (2783, 0.09733285267845754),
 (4254, 0.09733285267845754),
 (4403, 0.09733285267845754),
 (4472, 0.09733285267845754),
 (9, 0.0967301666813349),
 (334, 0.0967301666813349),
 (371, 0.09567297464698798),
 (412, 0.09567297464698798),
 (2237, 0.09567297464698798),
 (2552, 0.09567297464698798),
 (4545, 0.09558988911273408),
 (362, 0.09544271444636668),
 (791, 0.09544271444636668),
 (1569, 0.09544271444636668),
 (2558, 0.09544271444636668),
 (4201, 0.09544271444636668),
 (18, 0.09493290614465533),
 (11, 0.09464970485606021),
 (587, 0.09464970485606021),
 (660, 0.09365858115816941),
 (920, 0.09365858115816941),
 (978, 0.09365858115816941),
 (1274, 0.09365858115816941),
 (1355, 0.09365858115816941),
 (1470, 0.09365858115816941),
 (1682, 0.09365858115816941),
 (1688, 0.09365858115816941),
 (1717, 0.09365858115816941),
 (2392, 0.09365858115816941),
 (2484, 0.09365858115816941),
 (2588, 0.09365858115816941),
 (2641, 0.09365858115816941),
 (2646, 0.09365858115816941),
 (2816, 0.09365858115816941),
 (3535, 0.09365858115816941),
 (3718, 0.09365858115816941),
 (4331, 0.09365858115816941),
 (4502, 0.09365858115816941),
 (301, 0.09365858115816939),
 (129, 0.09269795493186431),
 (243, 0.09269795493186431),
 (279, 0.09269795493186431),
 (473, 0.09269795493186431),
 (596, 0.09269795493186431),
 (813, 0.09269795493186431),
 (1442, 0.09269795493186431),
 (1697, 0.09269795493186431),
 (3405, 0.09269795493186431),
 (785, 0.09243423333081695),
 (219, 0.09197090092274487),
 (244, 0.09197090092274487),
 (511, 0.09197090092274487),
 (1752, 0.09197090092274487),
 (2089, 0.09197090092274487),
 (2647, 0.09197090092274487),
 (3734, 0.09197090092274487),
 (230, 0.09183979479633063),
 (799, 0.09183979479633063),
 (239, 0.09125667909262308),
 (2566, 0.09125667909262308),
 (43, 0.09086217008485092),
 (602, 0.09086217008485092),
 (995, 0.09086217008485092),
 (1231, 0.09086217008485092),
 (1842, 0.09086217008485092),
 (3879, 0.09086217008485092),
 (12, 0.09037128496931669),
 (88, 0.09037128496931669),
 (167, 0.09037128496931669),
 (356, 0.09037128496931669),
 (400, 0.09037128496931669),
 (1304, 0.09037128496931669),
 (1476, 0.09037128496931669),
 (2247, 0.09037128496931669),
 (2955, 0.09037128496931669),
 (331, 0.08998425413316952),
 (2359, 0.08998425413316952),
 (2792, 0.08998425413316952),
 (2852, 0.08998425413316952),
 (3387, 0.08998425413316952),
 (3441, 0.08998425413316952),
 (3460, 0.08998425413316952),
 (4343, 0.08998425413316952),
 (4353, 0.08998425413316952),
 (274, 0.08977310580745099),
 (1902, 0.0891313035643173),
 (2111, 0.08903057122447033),
 (292, 0.08885233166386385),
 (564, 0.08885233166386385),
 (1025, 0.08885233166386385),
 (2656, 0.08885233166386385),
 (2864, 0.08885233166386385),
 (3320, 0.08885233166386385),
 (169, 0.08830215713766959),
 (270, 0.08830215713766959),
 (618, 0.08830215713766959),
 (1779, 0.08830215713766959),
 (2105, 0.08830215713766959),
 (2709, 0.08830215713766959),
 (2736, 0.08830215713766959),
 (3551, 0.08830215713766959),
 (479, 0.08797691788472335),
 (752, 0.08749572785196143),
 (1828, 0.08749572785196143),
 (2444, 0.08746392856766495),
 (23, 0.08740748201220976),
 (141, 0.08740748201220976),
 (389, 0.08740748201220976),
 (745, 0.08740748201220976),
 (794, 0.08740748201220976),
 (960, 0.08740748201220976),
 (1247, 0.08740748201220976),
 (1257, 0.08740748201220976),
 (3446, 0.08740748201220976),
 (3447, 0.08740748201220976),
 (143, 0.08671099695241201),
 (199, 0.08671099695241201),
 (827, 0.08671099695241201),
 (1526, 0.08671099695241201),
 (2876, 0.08671099695241201),
 (3554, 0.08671099695241201),
 (4516, 0.08671099695241201),
 (4587, 0.08671099695241201),
 (2, 0.08603090020146065),
 (457, 0.08603090020146065),
 (775, 0.08603090020146065),
 (1374, 0.08603090020146065),
 (2579, 0.08603090020146065),
 (3133, 0.08603090020146065),
 (4754, 0.08603090020146065),
 (234, 0.08594700851870801),
 (1017, 0.08594700851870801),
 (2350, 0.08594700851870801),
 (32, 0.08520286456846099),
 (217, 0.08520286456846099),
 (142, 0.08471737420873576),
 (894, 0.08471737420873576),
 (1095, 0.08471737420873576),
 (1140, 0.08471737420873576),
 (1585, 0.08471737420873576),
 (2300, 0.08471737420873576),
 (4560, 0.08471737420873576),
 (48, 0.08447772061910234),
 (190, 0.08447772061910234),
 (1303, 0.08447772061910234),
 (1635, 0.08447772061910234),
 (2966, 0.08447772061910234),
 (62, 0.0837707816583391),
 (381, 0.0837707816583391),
 (534, 0.0837707816583391),
 (1694, 0.0837707816583391),
 (3178, 0.0837707816583391),
 (3216, 0.0837707816583391),
 (3976, 0.0837707816583391),
 (4737, 0.0837707816583391),
 (1, 0.08346223261119858),
 (152, 0.08346223261119858),
 (203, 0.08346223261119858),
 (315, 0.08346223261119858),
 (547, 0.08346223261119858),
 (1684, 0.08346223261119858),
 (2124, 0.08346223261119858),
 (2382, 0.08321783316232578),
 (19, 0.0830812984794528),
 (403, 0.0830812984794528),
 (3903, 0.0830812984794528),
 (45, 0.08240856434303293),
 (2199, 0.08240856434303293),
 (39, 0.08226127456606226),
 (227, 0.08226127456606226),
 (341, 0.08226127456606226),
 (626, 0.08226127456606226),
 (787, 0.08226127456606226),
 (1205, 0.08226127456606226),
 (1745, 0.08226127456606226),
 (2163, 0.08226127456606226),
 (2657, 0.08226127456606226),
 (3138, 0.08226127456606226),
 (3299, 0.08226127456606226),
 (3468, 0.08226127456606226),
 (63, 0.08175191193132876),
 (501, 0.08175191193132876),
 (38, 0.08111071056538127),
 (242, 0.08111071056538127),
 (245, 0.08111071056538127),
 (306, 0.08111071056538127),
 (584, 0.08111071056538127),
 (812, 0.08111071056538127),
 (866, 0.08111071056538127),
 (901, 0.08111071056538127),
 (1267, 0.08111071056538127),
 (1515, 0.08111071056538127),
 (1660, 0.08111071056538127),
 (2335, 0.08111071056538127),
 (2640, 0.08111071056538127),
 (2667, 0.08111071056538127),
 (2861, 0.08111071056538127),
 (2873, 0.08111071056538127),
 (3525, 0.08111071056538127),
 (3924, 0.08111071056538127),
 (4492, 0.08111071056538127),
 (4568, 0.08111071056538127),
 (4626, 0.08111071056538127),
 (4641, 0.08111071056538127),
 (4654, 0.08111071056538127),
 (4657, 0.08111071056538127),
 (51, 0.08048436365855338),
 (164, 0.08000711205939975),
 (854, 0.08000711205939975),
 (899, 0.08000711205939975),
 (1323, 0.08000711205939975),
 (1743, 0.08000711205939975),
 (2679, 0.08000711205939975),
 (3762, 0.08000711205939975),
 (3814, 0.08000711205939975),
 (3849, 0.08000711205939975),
 (486, 0.07992075789278004),
 (103, 0.07987230638308718),
 (222, 0.07987230638308718),
 (1530, 0.07987230638308718),
 (2788, 0.07987230638308718),
 (4506, 0.07987230638308718),
 (1894, 0.0792740035289418),
 (16, 0.07894736842105264),
 (37, 0.07894736842105264),
 (241, 0.07894736842105264),
 (329, 0.07894736842105264),
 (1078, 0.07894736842105264),
 (1159, 0.07894736842105264),
 (2291, 0.07894736842105264),
 (3231, 0.07894736842105264),
 (4316, 0.07894736842105264),
 (193, 0.07878168645790681),
 (153, 0.07868894753646337),
 (776, 0.07868894753646337),
 (1043, 0.07868894753646337),
 (1824, 0.07868894753646337),
 (1922, 0.07868894753646337),
 (3726, 0.07868894753646337),
 (3830, 0.07868894753646337),
 (4279, 0.07868894753646337),
 (4473, 0.07868894753646337),
 (125, 0.07843304784240032),
 (286, 0.0781166566864507),
 (1655, 0.0781166566864507),
 (174, 0.07792865001991967),
 (402, 0.07792865001991967),
 (922, 0.07792865001991967),
 (1111, 0.07792865001991967),
 (2936, 0.07792865001991967),
 (3026, 0.07792865001991967),
 (3089, 0.07792865001991967),
 (3100, 0.07792865001991967),
 (3162, 0.07792865001991967),
 (4341, 0.07792865001991967),
 (1920, 0.07755667343294813),
 (3558, 0.07755667343294813),
 (1280, 0.0770085628656519),
 (40, 0.07694837640638656),
 (96, 0.07694837640638656),
 (101, 0.07694837640638656),
 (112, 0.07694837640638656),
 (207, 0.07694837640638656),
 (632, 0.07694837640638656),
 (737, 0.07694837640638656),
 (1287, 0.07694837640638656),
 (2215, 0.07694837640638656),
 (4266, 0.07694837640638656),
 (4624, 0.07694837640638656),
 (850, 0.07647191129018727),
 (1003, 0.07647191129018727),
 (1137, 0.07647191129018727),
 (1252, 0.07647191129018727),
 (1617, 0.07647191129018727),
 (2161, 0.07647191129018727),
 (2270, 0.07647191129018727),
 (2708, 0.07647191129018727),
 (3428, 0.07647191129018727),
 (4163, 0.07647191129018727),
 (70, 0.076004188790721),
 (82, 0.076004188790721),
 (235, 0.076004188790721),
 (349, 0.076004188790721),
 (492, 0.076004188790721),
 (1288, 0.076004188790721),
 (1519, 0.076004188790721),
 (2445, 0.076004188790721),
 (2914, 0.076004188790721),
 (4558, 0.076004188790721),
 (246, 0.07594632491572426),
 (2001, 0.07543142864047142),
 (3329, 0.07530940414109724),
 (98, 0.07509392614826384),
 (210, 0.07509392614826384),
 (361, 0.07509392614826384),
 (365, 0.07509392614826384),
 (503, 0.07509392614826384),
 (540, 0.07509392614826384),
 (680, 0.07509392614826384),
 (1007, 0.07509392614826384),
 (1291, 0.07509392614826384),
 (2159, 0.07509392614826384),
 (4043, 0.07509392614826384),
 (4203, 0.07509392614826384),
 (2252, 0.07492686492653551),
 (205, 0.07443229275647868),
 (800, 0.07443229275647868),
 (993, 0.07443229275647868),
 (1321, 0.07443229275647868),
 (1517, 0.07443229275647868),
 (1766, 0.07443229275647868),
 (2322, 0.07443229275647868),
 (2547, 0.07443229275647868),
 (2797, 0.07443229275647868),
 (3067, 0.07443229275647868),
 (3115, 0.07443229275647868),
 (3124, 0.07443229275647868),
 (4009, 0.07443229275647868),
 (4412, 0.07443229275647868),
 (4542, 0.07443229275647868),

In [59]:
def recommend(movie):
    movie_index = new_df[new_df["title"]==movie].index[0]
    distance = similarity[movie_index]
    movies_list = sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]]["title"])

In [60]:
recommend("Avatar")

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [61]:
new_df.iloc[2409]

id                                                    9675
title                                             Sideways
tags     two middle-ag men embark on a spiritu journey ...
Name: 2409, dtype: object

In [59]:
import pickle

In [60]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [62]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [64]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [65]:
new_df.columns

Index(['id', 'title', 'tags'], dtype='object')